name: Python CI without Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flask

      - name: Run Flask app
        run: |
          nohup python app.py &
          sleep 5
        shell: bash

      - name: Run tests if present
        run: |
          if [ -f test.py ]; then python test.py; else echo "No tests found."; fi
